version: 2

models:
  - name: dim_coche
    description: "Tabla de gold"
    config:
      materialized: incremental_alsa
      alias: Al_T_Dim_Vehicle
      unique_keys:
        - IdVehicle
        - IdTypeOrigin
      business_start_date: COALESCE(safe.parse_timestamp("%Y%M%d", (CAST(DateVehicleStart AS STRING))), "1900-1-1")
      cluster_by: ["modifdate", "validStartDate", "ValidEndDate", "DeleteDate"]
      modif_date: DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 3 DAY)
      version_date: CURRENT_TIMESTAMP()
      historic: True
      delete_strategy:
        type: target
      #delete_strategy:
      #  type: source
      #  source_unique_keys:
      #    - table_name: ["bq_dim_silver_com", "Al_T_Dim_Vehicle"]
      #      delete_clause: Null
      #      unique_keys:
      #        - IdVehicle: IdVehicle
      #        - IdTypeOrigin: IdTypeOrigin
