version: 2

models:
  - name: Al_T_Fact_VehicleOccupancy
    description: "Tabla de gold Ocupación Vehículos"
    config:
      materialized: incremental_alsa
      alias: Al_T_Fact_VehicleOccupancy
      unique_keys:
        - Line
        - TripID
        - TravelDate
        - BusNumber
        - OriginCode
        - OriginName
        - DestinationCode
        - DestinationName
        - SaleDate
        - DaysInAdvance
        - SeatsOffered
        - OccupiedOriginDest
        - OccupiedInitialFinal
        - AvailableOriginDest
        - AvailableInitialFinal
        - InfoDateFrom
        - InfoDateTo
        - StopDate
      business_start_date: CURRENT_TIMESTAMP()
      cluster_by: ["modifdate", "validStartDate", "ValidEndDate", "DeleteDate"]
      modif_date: DATE_SUB(CURRENT_DATE(), INTERVAL 2 DAY)
      version_date: CURRENT_TIMESTAMP()
      historic: True