version: 2

models:
  - name: Al_T_Dim_AlsaProviders
    description: "Tabla de gold Proveedores Alsa"
    config:
      materialized: incremental_alsa
      alias: Al_T_Dim_AlsaProviders
      unique_keys:
        - ThirdPartyCode
        - CompanyCode
      business_start_date: CURRENT_TIMESTAMP()
      cluster_by: ["modifdate", "validStartDate", "ValidEndDate", "DeleteDate"]
      modif_date: DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY)
      version_date: CURRENT_TIMESTAMP()
      historic: True