version: 2

models:
  - name: Al_T_Fact_PositionsControl
    description: "Tabla Fact Control Posiciones Gold"
    config:
      materialized: incremental_alsa
      alias: Al_T_Fact_PositionsControl
      unique_keys:
        - DateHour
        - IdSystem
      cluster_by: ["ModifDate", "validStartDate", "ValidEndDate", "DeleteDate"]
      modif_date: TIMESTAMP_TRUNC(TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY), DAY)
      filter_final_tb: "AND final.DateHour >= TIMESTAMP_TRUNC(TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY), DAY)"
      version_date: CURRENT_TIMESTAMP()
      business_start_date: CURRENT_TIMESTAMP()
      historic: True
      delete_strategy:
        type: target # source/target
        delete_clause: "DateHour >= TIMESTAMP_TRUNC(TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY), DAY)"
        
