version: 2

models:
  - name: dim_evolcochetaller
    description: "Tabla de gold"
    config:
      enabled: True
      materialized: incremental_alsa
      alias: Al_T_Dim_VehicleGarageEvol
      unique_keys:
        - IdVehicle
        - IdCompanyGarage
        - DateRelationshipStart
      business_start_date: COALESCE(safe.parse_timestamp("%Y%M%d", (CAST(DateRelationshipStart AS STRING))), "1900-1-1")
      cluster_by: ["modifdate", "validStartDate", "ValidEndDate", "DeleteDate"]
      modif_date: DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 3 DAY)
      version_date: CURRENT_TIMESTAMP()
      historic: True
      delete_strategy:
        type: target
      #delete_strategy:
      #  type: source
      #  source_unique_keys:
      #    - table_name: ["bq_dim_silver_com", "Al_T_Dim_VehicleGarageEvol"]
      #      delete_clause: Null
      #      unique_keys:
      #        - IdVehicle: IdVehicle
      #        - IdCompanyGarage : IdCompanyGarage
      #        - DateRelationshipStart : DateRelationshipStart
