version: 2

models:
  - name: Al_T_Lkt_SecondaryVehicleProvider
    description: "Tabla Lkt Silver"
    config:
      materialized: incremental_alsa
      alias: Al_T_Lkt_SecondaryVehicleProvider
      unique_keys:
        - IdVehicle
        - System
      # business_start_date: COALESCE(safe.parse_timestamp("%Y%M%d", CAST(DateVehicleStart AS STRING)), "1900-1-1")
      cluster_by: ["modifdate", "validStartDate", "ValidEndDate", "DeleteDate"]
      modif_date: DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 3 DAY)
      version_date: CURRENT_TIMESTAMP()
      business_start_date: CURRENT_TIMESTAMP()
      historic: True
      delete_strategy:
        type: source # source/target
        source_unique_keys:
          - table_name: ["bq_com_slv", "Al_T_Lkt_SecondaryVehicleProvider"]
            delete_clause: Null
            unique_keys:
              - IdVehicle: IdVehicle
              - System: System
