version: 2

models:
  - name: Al_T_Fact_ServiceActivity_PW
    description: "Tabla Fact Silver"
    config:
      alias: Al_T_Fact_ServiceActivity_PW
      materialized: incremental_alsa
      unique_keys:
        - HashedKey
      cluster_by: ["DateTravel_PARTITION", "validStartDate", "ValidEndDate", "DeleteDate"]
      partition_by: 
        field: DateTravel_PARTITION
        data_type: timestamp
        granularity: day
      modif_date: TIMESTAMP_TRUNC(TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 12 DAY), DAY)
      filter_final_tb: "AND final.DateTravel_PARTITION >= TIMESTAMP_TRUNC(TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 12 DAY), DAY)"
      version_date: CURRENT_TIMESTAMP()
      business_start_date: CURRENT_TIMESTAMP()
      historic: True
      delete_strategy:
        type: target
        delete_clause: "DateTravel_PARTITION >= TIMESTAMP_TRUNC(TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 12 DAY), DAY)"
