version: 2

models:
  - name: Al_T_Lkt_VehicleEvolLV
    description: "Tabla Lkt Gold"
    config:
      materialized: table
      alias: Al_MV_Lkt_VehicleEvolLV
      unique_keys:
        - IdCompany
        - IdVehicle
      business_start_date: COALESCE(safe.parse_timestamp("%Y%M%d", CAST(DateVehicleStart AS STRING)), "1900-1-1")
      cluster_by: ["IdCompany", "IdVehicle", "DateVehicleStart", "LicensePlate"]
      modif_date: DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 3 DAY)
      version_date: CURRENT_TIMESTAMP()
      business_start_date: CURRENT_TIMESTAMP()
      historic: True
      delete_strategy:
        type: source # source/target
        source_unique_keys:
          - table_name: ["bq_com_slv", "Al_T_Lkt_VehicleEvolLV_Stg1"]
            delete_clause: Null
            unique_keys:
              - IdCompany: IdCompany
              - IdVehicle: IdVehicle
              - DateVehicleStart: DateVehicleStart
              - LicensePlate: LicensePlate
