version: 2

models:
  - name: Al_T_Dim_Systems
    description: "Tabla de Gold ObtExplot"
    config:
      materialized: incremental_alsa
      alias: Al_T_Dim_Systems
      unique_keys:
        - IdExplot
      cluster_by: ["modifdate", "validStartDate", "ValidEndDate", "DeleteDate"]
      modif_date: DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 3 DAY)
      version_date: CURRENT_TIMESTAMP()
      historic: True
      delete_strategy:
        type: target
