version: 2

sources:
  - name: dbt_semantic_layer
    database: propellingtech-demo-customers
    schema: dbt_semantic_layer_demo
    tables:
      - name: dim_customers
        description: "Dimension table containing customer information"
      - name: fct_orders
        description: "Fact table containing order transactions"
      - name: order_items
        description: "Table containing individual items within orders"