version: 2

sources:
  - name: dbt_semantic_layer_demo
    database: propellingtech-demo-customers
    schema: dbt_semantic_layer_demo
    tables:
      - name: dim_customers
        description: Customer dimension table containing customer details
        columns:
          - name: customer_id
            description: Unique identifier for each customer
          - name: name
            description: Customer name
            
      - name: fct_orders
        description: Fact table containing order transactions
        columns:
          - name: order_id
            description: Unique identifier for each order
          - name: customer_id
            description: Foreign key to dim_customers
          - name: order_total
            description: Total amount of the order
          - name: ordered_at
            description: Timestamp when the order was placed
            
      - name: order_items
        description: Order items detail table
        columns:
          - name: order_item_id
            description: Unique identifier for each order item
          - name: order_id
            description: Foreign key to fct_orders
          - name: is_food_item
            description: Flag indicating if the item is a food item (1 = yes, 0 = no)
          - name: is_drink_item
            description: Flag indicating if the item is a drink item (1 = yes, 0 = no)
