version: 2

models:
  - name: dim_zonas
    description: "Tabla de Gold"
    config:
      materialized: incremental_alsa
      alias: Al_T_Dim_Zone
      unique_keys: ["IdZone"]
      business_start_date: parse_timestamp("%Y%M%d", CAST(DateZoneStart AS STRING))
      cluster_by: ["modifdate", "validStartDate", "ValidEndDate", "DeleteDate"]
      modif_date: DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 3 DAY)
      version_date: CURRENT_TIMESTAMP()
      historic: True
      delete_strategy:
        type: target
      #delete_strategy:
      #  type: source
      #  source_unique_keys:
      #    - table_name: ["bq_dim_silver_com", "Al_T_Dim_Zone"]
      #      delete_clause: Null
      #      unique_keys:
      #        - IdZone: IdZone
