version: 2

models:
  - name: dim_evolcoche
    description: "Tabla de gold"
    config:
      materialized: incremental_alsa
      alias: Al_T_Dim_VehicleEvol
      unique_keys:
        - IdCompany
        - IdVehicle
        - DateVehicleStart
        - IdTypeOrigin
      business_start_date: COALESCE(safe.parse_timestamp("%Y%M%d", CAST(DateVehicleStart AS STRING)), "1900-1-1")
      cluster_by: ["modifdate", "validStartDate", "ValidEndDate", "DeleteDate"]
      modif_date: DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 3 DAY)
      version_date: CURRENT_TIMESTAMP()
      historic: True
      delete_strategy:
        type: target
