version: 2

models:
  - name: Al_T_Agg_Activity_Date
    description: "Agg from silver TotalKM and TotalHours for activity vehicle for IdDivision, IdEmploye, IdZu, IdCompany, IdDriver, IdCg, LicensPlate, Vehicle, Date, DateTravel, DateDeparture per day"
    config:
      materialized: incremental_alsa
      alias: Al_T_Agg_Activity_Date
      unique_keys:
        - IdDivision
        - IdZu
        - IdZone
        - IdCg
        - IdVehicleCompany
        - IdDriver
        - IdVehicle
        - Date
        - DateDeparture
        - DateTravel
        - LicensePlate
        - IdEmployee
        - ActivityDate
      cluster_by: ["DateTravel", "Date", "DateDeparture", "IdVehicle"]
      modif_date: DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 3 DAY)
      version_date: CURRENT_TIMESTAMP()
      business_start_date: CURRENT_TIMESTAMP()
      historic: True
      delete_strategy:
        type: target
