version: 2

models:
  - name: dim_fechascierre
    description: "Tabla de gold"
    config:
      materialized: incremental_alsa
      alias: Al_T_Dim_ClosingDates
      unique_keys:
        - PeriodNumber
        - IdReport
      cluster_by: ["modifdate", "validStartDate", "ValidEndDate", "DeleteDate"]
      modif_date: DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 3 DAY)
      version_date: CURRENT_TIMESTAMP()
      historic: True
      delete_strategy:
        type: target

