version: 2

models:
  - name: Al_T_Fact_Sales
    description: "Tabla de gold Ventas"
    config:
      materialized: incremental_alsa
      alias: Al_T_Fact_Sales
      unique_keys:
        - OnlyHint
        - DocumentNumber
        - OriginCode
        - OriginName
        - DestinationCode
        - DestinationName
        - VACode
        - LineCode
        - LineName
        - TripID
        - BusNumber
        - LineCategory
        - GroupedChannel
        - SaleDate
        - TravelDate
        - DepartureHour
        - StopDate
        - StopHour
        - PromotionCode
        - PromotionName
        - DiscountCode
        - DiscountName
        - IsCancelledFlag
        - TicketAmountNetVAT
        - ClasPassAmountNetVAT
        - DigitalPassAmountNetVAT
        - Passengers
        - ClasPassPassengers
        - DigitalPassPassengers
        - InfoDateFrom
        - InfoDateTo
      business_start_date: CURRENT_TIMESTAMP()
      cluster_by: ["modifdate", "validStartDate", "ValidEndDate", "DeleteDate"]
      modif_date: DATE_SUB(CURRENT_DATE(), INTERVAL 2 DAY)
      version_date: CURRENT_TIMESTAMP()
      historic: True