my-bigquery-db:
  target: dev
  outputs:
    dev:
        type: bigquery
        method: oauth
        project: propellingtech-demo-customers
        execution_project: propellingtech-demo-customers
        dataset: dbt_semantic_layer_demo
        location: europe-west1
        threads: 4
   