version: 2

models:
  - name: Al_T_Dim_RouteJourneys
    description: "Tabla de gold Trayectos-Ruta"
    config:
      materialized: incremental_alsa
      alias: Al_T_Dim_RouteJourneys
      unique_keys:
        - IdJourney
      business_start_date: CURRENT_TIMESTAMP()
      cluster_by: ["modifdate", "validStartDate", "ValidEndDate", "DeleteDate"]
      version_date: CURRENT_TIMESTAMP()
      historic: True
