version: 2

models:
  - name: dim_gc
    description: "Tabla de Gold"
    config:
      materialized: incremental_alsa
      alias: Al_T_Dim_ContractGroup
      unique_keys: ["IdCG"]
      cluster_by: ["modifdate", "validStartDate", "ValidEndDate", "DeleteDate"]
      business_start_date: COALESCE(safe.parse_timestamp("%Y%M%d", (CAST(DateCgStart AS STRING))), "1900-1-1")
      modif_date: DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 3 DAY)
      version_date: CURRENT_TIMESTAMP()
      historic: True
      delete_strategy:
        type: target
