version: 2

models:
  - name: dim_uz
    description: "Tabla de gold"
    config:
      materialized: incremental_alsa
      alias: Al_T_Dim_ZonalUnit
      unique_keys: ["IdZu"]
      business_start_date: parse_timestamp("%Y%M%d", CAST(DateZuStart AS STRING))
      cluster_by: ["modifdate", "validStartDate", "ValidEndDate", "DeleteDate"]
      modif_date: DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 3 DAY)
      version_date: CURRENT_TIMESTAMP()
      historic: True
      delete_strategy:
        type: target